#!/usr/bin/env sh

CWD=$1
CMD=$2
VIM_PID=$3

TITLE="vim-test-output-$VIM_PID"

# need to create a window first
if [[ `kitty @ ls | grep -c '            "title": "'$TITLE` -eq 0 ]]; then
  kitty @ --to "$KITTY_LISTEN_ON" new-window --title "$TITLE" --keep-focus --window-type os --cwd $CWD $SHELL
fi

kitty @ --to "$KITTY_LISTEN_ON" send-text --match title:"$TITLE" --exclude-active "$CMD\x0d"
