git:
  pagers:
    - pager: delta --dark --paging=never
  overrideGpg: true
customCommands:
  - key: <c-p>
    context: localBranches
    description: Create pull request (git pr)
    command: git pr
    output: terminal
